version: '3.2'
services:
  api:
    container_name: api
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING="Server=(sql-server)\mssqllocaldb;Database=MyDatabase;Trusted_Connection=True;"
    ports:
      - "8080:80"
    volumes:
      - .:/app
    links:
      - sql-server
  sql-server:
    container_name: sql-server
    image: microsoft/mssql-server-linux:2017-CU8
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=A1b2C3d4
    ports:
      - "1433:1433"
