version: '3.2'
services:
  api:
    container_name: financial
    build: FinancialApi/
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_CONNECTION=Server=sql-server;Database=Financial;User=sa;Password=@A1b2?C3d4
      - QUEUE_CONNECTION=rabbitmq;usermq;usermq
    ports:
      - "8080:8080"
    volumes:
      - ./FinancialApi/:/app
    command: ["./wait-for-it.sh", "sql-server:1433", "rabbitmq:5672","--", "./app.sh"]
    links:
      - sql-server
      - rabbitmq
  sql-server:
    container_name: sql-server
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@A1b2?C3d4
    ports:
      - "1433:1433"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=usermq
      - RABBITMQ_DEFAULT_PASS=usermq
    ports:
      - "5672:5672"
      - "15672:15672"
