version: '3.2'
services:
  api:
    container_name: api
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING="Data Source=sql-server,1433;Initial Catalog=Database;User ID=sa;Password=@A1b2 C3d4"
    ports:
      - "8080:80"
    volumes:
      - .:/app
    links:
      - sql-server
  sql-server:
    container_name: sql-server
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@A1b2 C3d4
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
